# Generated by Django 2.2.5 on 2021-08-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210811_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='b_photo',
        ),
        migrations.CreateModel(
            name='BoardPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Board')),
            ],
        ),
    ]
