# Generated by Django 2.2.5 on 2021-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20210811_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='qna',
            name='b_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tips',
            name='b_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
