# Generated by Django 2.2.5 on 2021-08-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210812_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_photo',
            field=models.ImageField(blank=True, default='../media/noimage.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='qna',
            name='b_photo',
            field=models.ImageField(blank=True, default='../media/noimage.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tips',
            name='b_photo',
            field=models.ImageField(blank=True, default='../media/noimage.jpg', null=True, upload_to=''),
        ),
    ]
