# Generated by Django 2.2.5 on 2021-08-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20210813_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_title',
            field=models.TextField(max_length=30),
        ),
    ]
