# Generated by Django 2.2.5 on 2021-08-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20210813_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='qna',
            name='b_content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='tips',
            name='b_content',
            field=models.TextField(max_length=2000),
        ),
    ]
