# Generated by Django 2.2.5 on 2021-08-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20210813_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tips',
            name='b_content',
            field=models.TextField(),
        ),
    ]
